version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:app
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saitama123
